@echo off
set PATH=%PATH:Z:/abel/Develop/b0-toolskits/compiler/CMake.app/Contents/MacOS;=%
set PATH=%PATH:Z:/abel/Develop/b0-toolskits/winLibraries/Qt/5.8/android_x86/bin;=%
set PATH=%PATH:Z:/abel/Develop/b0-toolskits/winAndroidLibraries/Java/jdk1.8.0_131/bin;=%
set PATH=%PATH:Z:/abel/Develop/b0-toolskits/winAndroidLibraries/android-sdk-linux;=%
set PATH=%PATH:Z:/abel/Develop/b0-toolskits/winAndroidLibraries/android-sdk-linux/platform-tools;=%
set PATH=%PATH:Z:/abel/Develop/b0-toolskits/winAndroidLibraries/android-sdk-linux/build-tools;=%
set PATH=%PATH:Z:/abel/Develop/b0-toolskits/winAndroidLibraries/android-sdk-linux/tools;=%
set PATH=%PATH:Z:/abel/Develop/b0-toolskits/winAndroidLibraries/apache-ant-1.10.1/bin;=%
set PATH=%PATH:Z:/abel/Develop/b0-toolskits/winAndroidLibraries/android-ndk-r13b/toolchains/x86-4.9/prebuilt/darwin-x86_64/bin;=%
set ANDROID_API_VERSION=
set ANDROID_SDK_ROOT=
set ANDROID_NDK_ROOT=
set ANDROID_NDK_HOST=
set ANDROID_NDK_TOOLCHAIN_PREFIX=
set ANDROID_NDK_TOOLCHAIN_VERSION=
set ANDROID_NDK_PLATFORM=
set NDK_TOOLCHAIN_PATH=
set NDK_TOOLS_PREFIX=
set PYCMD_MYNAME=
set a_special_var_const=
set QKIT=
set QTDIR=
set QTSPEC=
set QTCONFIG=
set JAVA_HOME=
set CLASSPATH=
